### PR TITLE
Simple pi button

### PR DESCRIPTION
**Pull request by itaki**
This defines the Led class in the device_library

Use simple-light-with-buttons.json config.

Updated the config json to have a preferences dictionary for the class

I know we talked about renaming this class to "Light" but then after our conversation about importing I was thinking maybe it's a moot point. But we could still talk about it.

### CODE REVIEW

**Comment by itaki** [comment]
Good notes! Thanks.

**Addressing this note : "f"something asked me to be off but something else is still on so I'm not going off yet")"**
_Add what device this refers to_
I agree, however, I don't know to access what device broadcast the event. This would work itself out pretty easily if we had that self.devices_who_want_me_on = [] list working.

Having thought more about this, the note is wrong. I'm not sure that it matters to a user, but it would be more accurate to say "{device} sent an event that would normally turn me off, but I'm waiting on {self.devices_who_want_me_on} before I can turn off"

_This should be a debug instead of an info_
I guess I am curious when info would be used. This seems like the exact type of statement that I'd want in the console as a shop owner. "I hit that damn button 3 freaking times and the light still isn't going off!!! What the hell is the problem!!!"
Looks at console. "Oh, the saw is still on.... duh". Turns saw off. Light goes out. 

Maybe I'm wrong about what INFO is used for?

**self.kill_timer function**
Looks like a new timer gets created so you have to cancel it or else you can do things like hit the delayed off like 10 times. Then you can't turn the light on because the light keeps getting turned off until all the timers run out. 

So it makes sense that _any_ action should first cancel the timer if there is one. 

But need your help on this one. So I put the try: except: clause in there because the _first time_ you try to cancel the timer, if there isn't one, it breaks. However, after that it never gets to the exception because even if you cancel() the timer, that doesn't remove it. 

I'm not sure it needs to be removed, maybe I'm over thinking it. 

Also, if I put a kill_timer in the force off, kill_timer runs twice when you hit a delayed off or delayed blink off. It runs when you hit it and then again right when it forces the light off. Not sure if this is a problem either.

**self.light.is_lit**
This is asking the light if it's on. I originally had this just as self.light.toggle(), but since it shouldn't go off if there are other devices that want it on, I needed to break it out into separate functions for each ask.

I could also do this by setting a variable like self.am_i_on = True, but since GPIOZero already keeps the state in is_lit, I thought it cleaner to just use that. 

However, I'm leaning away from that now because as we flesh out more devices I imagine that state will be a thing we will want to standardize across all the devices. 

Since GPIOZERO isn't going to work on, say, a servo hat, we won't be able to ask it if a gate is open unless we track it. We'll probably want something like gate.is_open = True or something. And if that's the case maybe we should go ahead and do that now with lights.

Another point is that if an LED is _NOT_ on the regular GPIO pins, we can't use the GPIOZERO classes. This means our fancy pants Led class I just wrote won't work at all to run an LED connected to a servo hat  or gpio expansion board or anything that isn't one of the 30ish pins that are available on the pi.

We could extend the GPIO library, or just write our own class entirely. Though I don't want to do that and I think you don't either. 
But I'd also be opposed to having 2 entirely separate LED classes or one big clusterclass.

_2 classes option_
Have GPIO_Led class that uses GPIOZERO
Have a Servo_Led class that uses some other code to control an Led at that address

_clusterclass option_
Have on class that looks at ["connection"]["bus'] and decides which methods it will use for what thing.

_fresh class_
Write our own class that does things like blink or pulse or PWM but can do it on any pin, GPIO or servo hat or GPIO extender or whatever pin that's out there. 

Thoughts?

**Comment by bigandy99** [comment]
Work needed before merging:
- change toggle behavior to not call force off
- rename device classes to include Gpio (maybe also renamed Led to ShopLight?)
- fully test and debug - locally and on Pi

**Comment by itaki** [comment]
Weird that I have double commits. Must still be doing something wrong in vscode.

This shit is tight. It works toggling and using separate buttons for on and force off.

Still needs to be tested with a keyboard, but I think this is there.

**Comment by itaki** [comment]
Another weird thing happened. I merged main with this branch and like nothing happened. I even tried using the command line and merge and it said merge was successful, but none of the code was updated. So I was messing around with it and I _think_ I got everything updated, but I'm not totally sure how to check. I could try merging main again I guess. 

Anyway, the keyboard works in this branch now and it's been tested on the pi.

**Pull request merged**
