### PR TITLE
Mock pins warning

### PR DESCRIPTION
**Pull request by itaki**
Added a warning message via logging that says "USING MOCK PINS!"

### CODE REVIEW

**Comment by bigandy99** [comment]
There's a lot more in here than just adding that warning! 

I'm okay with having some simple test files but let's not clutter them in the app root. Perhaps move to the utils folder or something similar?

What's the reason for changing the default logging level? Generally speaking, debugging shouldn't be our default but something we do when we are debugging something. I think it's cleaner to keep it at WARN level and then if you're working on something you want to quickly see you can just use the warning level and you'll actually be able to see it even faster than fishing it out from an ever-growing list of debug statements.

**Comment by bigandy99** [comment]
A couple issues remain:
- There's still a newly added print statement in the device library that is not needed
- The log level is "WARNING" not "WARN" (did you test this? and if so did "WARNING also work?")

**Comment by itaki** [comment]
My bad. I should have double checked both those things.

**Comment by bigandy99** [comment]
Looks good!

**Pull request merged**
